#    PyTorch Basics

In [1]:
2.# Create a tensor of shape (3, 4) with random values.

import torch

a=torch.rand(2,3)
a

tensor([[0.5309, 0.6994, 0.9826],
        [0.4204, 0.8653, 0.4773]])

In [2]:
# 3.Create a tensor with all ones and another with all zeros.
b=torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
c=torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:

# 4.Convert a NumPy array to a PyTorch tensor.

import numpy as np
arr =np.array([[1,2,3],[4,5,6]])

tensor=torch.from_numpy(arr)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [5]:
# 5.Slice a tensor to get the first 2 rows and 2 columns.

x=torch.rand(4,4)
sliced=x[:3,2:4]
sliced

tensor([[0.5015, 0.5426],
        [0.5238, 0.9077],
        [0.2228, 0.2682]])

In [6]:
# 6.How do you perform matrix multiplication in PyTorch?
a = torch.randn(2, 3)
b = torch.randn(3, 4)
c = torch.matmul(a, b)

c

tensor([[-0.8405,  1.0417,  0.7773, -1.2449],
        [-0.1005, -1.6992, -0.5955,  1.3698]])

In [7]:
# 7.Create a tensor that requires gradients.

x = torch.tensor([2.0], requires_grad=True)
x

tensor([2.], requires_grad=True)

In [8]:
# 8. Demonstrate .backward() on a scalar loss.

x = torch.tensor([2.0], requires_grad=True)
y = x ** 2 + 3 * x + 5
y.backward()
print(x.grad)

tensor([7.])


In [9]:
# 9.Find the gradient of y = x ** 2 + 3 * x + 5 at x = 3
x = torch.tensor([3.0], requires_grad=True)
y = x ** 2 + 3 * x + 5
y.backward()S
print(x.grad)

SyntaxError: invalid syntax (3913795721.py, line 4)

In [ ]:
# 10.Explain .detach() and its use.
"""
 .detach() creates a new tensor that shares storage but without gradients.

 
 Used to stop a tensor from tracking operations in computation graphs.


"""

y = x * 2
y_detached = y.detach()
y_detached

tensor([6.])

In [ ]:
# 11.How to check if a tensor is on CPU or GPU?



In [ ]:
# 12.How to transfer a tensor to GPU?



In [ ]:
# 13.What is torch.rand_like() and when would you use it?



In [ ]:
# 14.Create a tensor and clone it. Change the clone and prove the original is unaffected.



In [ ]:
# 15.Create a 1D tensor and reshape it into (5, 2).



In [ ]:
# 16.What does .unsqueeze() do?



In [ ]:
# 17.How does broadcasting work in PyTorch?



In [ ]:
# 18.Add two tensors of different shapes using broadcasting.



In [ ]:
# 19.Explain .item() and .numpy() in context of tensors.



In [ ]:
# 20.Explain difference between in-place and out-of-place operations with examples.