#    PyTorch Basics

In [1]:
2.# Create a tensor of shape (3, 4) with random values.

import torch

a=torch.rand(2,3)
a

tensor([[0.1508, 0.7520, 0.3537],
        [0.5196, 0.7429, 0.0380]])

In [2]:
# 3.Create a tensor with all ones and another with all zeros.
b=torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
c=torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:

# 4.Convert a NumPy array to a PyTorch tensor.

import numpy as np
arr =np.array([[1,2,3],[4,5,6]])

tensor=torch.from_numpy(arr,de)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [5]:
# 5.Slice a tensor to get the first 2 rows and 2 columns.

x=torch.rand(4,4)
sliced=x[:3,2:4]
sliced

tensor([[0.1409, 0.0837],
        [0.2471, 0.0125],
        [0.5403, 0.1594]])

In [6]:
# 6.How do you perform matrix multiplication in PyTorch?
a = torch.randn(2, 3)
b = torch.randn(3, 4)
c = torch.matmul(a, b)

c

tensor([[-0.7169, -2.0994,  0.4712, -0.8350],
        [ 3.4109, -2.8444,  1.1174,  0.2312]])

In [7]:
# 7.Create a tensor that requires gradients.

x = torch.tensor([2.0], requires_grad=True)
x

tensor([2.], requires_grad=True)

In [8]:
# 8. Demonstrate .backward() on a scalar loss.

x = torch.tensor([2.0], requires_grad=True)
y = x ** 2 + 3 * x + 5
y.backward()
print(x.grad)

tensor([7.])


In [9]:
# 9.Find the gradient of y = x ** 2 + 3 * x + 5 at x = 3
x = torch.tensor([3.0], requires_grad=True)
y = x ** 2 + 3 * x + 5
y.backward()
print(x.grad)

tensor([9.])


In [10]:
# 10.Explain .detach() and its use.
"""
 .detach() creates a new tensor that shares storage but without gradients.

 
 Used to stop a tensor from tracking operations in computation graphs.


"""

y = x * 2
y_detached = y.detach()
y_detached

tensor([6.])

In [12]:
# 11.How to check if a tensor is on CPU or GPU?

x.device

device(type='cpu')

In [13]:
# 12.How to transfer a tensor to GPU?

device=torch.device('cuda' if torch.cuda.is_available else 'cpu')
x.to(device)

tensor([3.], device='cuda:0', grad_fn=<ToCopyBackward0>)

In [16]:
# 13.What is torch.rand_like() and when would you use it?

# It creates a random tensor with the same shape and dtype as the given tensor.

ten=torch.ones(2,3)

rand=torch.rand_like(ten)
rand

tensor([[0.8537, 0.7834, 0.7244],
        [0.6221, 0.3406, 0.4966]])

In [20]:
# 14.Create a tensor and clone it. Change the clone and prove the original is unaffected.

ten=torch.ones(2,3)

ten_copy=ten.clone()

ten[0][0]=3
ten

tensor([[3., 1., 1.],
        [1., 1., 1.]])

In [21]:
ten_copy

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
# 15.Create a 1D tensor and reshape it into (5, 2).

b=torch.arange(1,11,1,device='cuda')
b.view(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], device='cuda:0')

In [38]:
# 16.What does .unsqueeze() do?
'''
Adds a dimension of size 1 at a specified position.

'''
c=torch.tensor([1,2,3,4,5])
c.shape

torch.Size([5])

In [39]:
c_unsqueeze=c.unsqueeze(1)
c_unsqueeze.shape

torch.Size([5, 1])

In [40]:
c_unsqueeze=c.unsqueeze(0)
c_unsqueeze.shape

torch.Size([1, 5])

In [ ]:
# 17.How does broadcasting work in PyTorch?

# PyTorch automatically expands tensors to be compatible for element-wise operations without copying data.


In [45]:
# 18.Add two tensors of different shapes using broadcasting.

a=torch.rand(3,1)
b=torch.rand(1,4)
c=a+b


In [46]:
# 19.Explain .item() and .numpy() in context of tensors.
'''
.item() converts a 1-element tensor to a Python scalar.

.numpy() converts a CPU tensor to a NumPy array (not allowed on GPU).

'''

x = torch.tensor([10.0])
print(x.item())       # 10.0
print(x.numpy())      # array([10.])

10.0
[10.]


In [47]:
# 20.Explain difference between in-place and out-of-place operations with examples.
'''
In-place: modifies the data directly and has a __ at the end (e.g., .add_())

Out-of-place: returns a new tensor, original remains unchanged.

'''

x = torch.tensor([1.0])
x.add_(2)   # in-place
# vs
x = torch.tensor([1.0])
y = x + 2   # out-of-place
