#    PyTorch Basics

In [3]:
2.# Create a tensor of shape (3, 4) with random values.

import torch

a=torch.rand(2,3)
a

tensor([[0.8490, 0.7728, 0.1322],
        [0.1381, 0.6804, 0.4502]])

In [4]:
# 3.Create a tensor with all ones and another with all zeros.
b=torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
c=torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:

# 4.Convert a NumPy array to a PyTorch tensor.

import numpy as np
arr =np.array([[1,2,3],[4,5,6]])

tensor=torch.from_numpy(arr)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [7]:
# 5.Slice a tensor to get the first 2 rows and 2 columns.

x=torch.rand(4,4)
sliced=x[:3,2:4]
sliced

tensor([[0.7062, 0.8229],
        [0.2443, 0.1213],
        [0.4259, 0.0842]])

In [12]:
# 6.How do you perform matrix multiplication in PyTorch?
a = torch.randn(2, 3)
b = torch.randn(3, 4)
c = torch.matmul(a, b)

c

tensor([[ 1.1788,  2.2788,  0.2688, -4.1562],
        [ 0.9644, -3.1611, -5.3729, -4.1888]])

In [14]:
# 7.Create a tensor that requires gradients.

x = torch.tensor([2.0], requires_grad=True)
x

tensor([2.], requires_grad=True)

In [17]:
# 8. Demonstrate .backward() on a scalar loss.

x = torch.tensor([2.0], requires_grad=True)
y = x ** 2 + 3 * x + 5
y.backward()
print(x.grad)

tensor([7.])


In [ ]:
# 9.Find the gradient of y = x ** 2 + 3 * x + 5 at x = 3
x = torch.tensor([3.0], requires_grad=True)
y = x ** 2 + 3 * x + 5
y.backward()S
print(x.grad)

tensor([9.])


In [23]:
# 10.Explain .detach() and its use.
"""
 .detach() creates a new tensor that shares storage but without gradients.

 
 Used to stop a tensor from tracking operations in computation graphs.


"""

y = x * 2
y_detached = y.detach()
y_detached

tensor([6.])

In [ ]:
How to check if a tensor is on CPU or GPU?



In [ ]:
How to transfer a tensor to GPU?



In [ ]:
What is torch.rand_like() and when would you use it?



In [ ]:
Create a tensor and clone it. Change the clone and prove the original is unaffected.



In [ ]:
Create a 1D tensor and reshape it into (5, 2).



In [ ]:
What does .unsqueeze() do?



In [ ]:
How does broadcasting work in PyTorch?



In [ ]:
Add two tensors of different shapes using broadcasting.



In [ ]:
Explain .item() and .numpy() in context of tensors.



In [ ]:
Explain difference between in-place and out-of-place operations with examples.