In [1]:
# create model

import torch
import torch.nn as nn

class Model(nn.Module):

     '''
    def __init__(self, num_features):

        super().__init__()
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
     '''
     '''

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)            
        out=self.sigmoid(out)
        return out

     '''

 # using sequential containers
     def __init__(self, num_features):

        super().__init__()
        self.network=nn.Sequential( 
                nn.Linear(num_features,3),
                nn.ReLU(),
                nn.Linear(3,1),
                nn.Sigmoid()
            )
     def forward(self,features):
         out=self.network(features)
         return out


In [2]:
# create dataset

features=torch.rand(10,5)

# create model

model=Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5789],
        [0.5603],
        [0.5607],
        [0.5605],
        [0.5602],
        [0.5605],
        [0.5666],
        [0.5932],
        [0.5607],
        [0.5599]], grad_fn=<SigmoidBackward0>)

In [3]:
# show modelweights

# model.linear1.weight

# Access first Linear layer's weights
model.network[0].weight



Parameter containing:
tensor([[-0.2005,  0.1188,  0.2907, -0.3667, -0.4409],
        [-0.0179, -0.3628, -0.4447, -0.2752,  0.1754],
        [ 0.0744, -0.3209,  0.1005, -0.3906,  0.3237]], requires_grad=True)

In [4]:
# model.linear1.bias


In [5]:
# Access second Linear layer's weights
model.network[2].weight
#model.linear2.weight

Parameter containing:
tensor([[-0.0144,  0.5632, -0.0160]], requires_grad=True)

In [6]:
# model.linear2.bias

print(model.network[0].bias)
print('='*50)
print(model.network[2].bias)


Parameter containing:
tensor([ 0.2886,  0.3949, -0.4057], requires_grad=True)
Parameter containing:
tensor([0.2438], requires_grad=True)


In [7]:
pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


In [8]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00