In [24]:
# create model

import torch
import torch.nn as nn

class Model(nn.Module):

     '''
    def __init__(self, num_features):

        super().__init__()
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
     '''
     '''

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)            
        out=self.sigmoid(out)
        return out

     '''

 # using sequential containers
     def __init__(self, num_features):

        super().__init__()
        self.network=nn.Sequential( 
                nn.Linear(num_features,3),
                nn.ReLU(),
                nn.Linear(3,1),
                nn.Sigmoid()
            )
     def forward(self,features):
         out=self.network(features)
         return out


In [25]:
# create dataset

features=torch.rand(10,5)

# create model

model=Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5699],
        [0.5699],
        [0.5699],
        [0.5699],
        [0.5699],
        [0.5699],
        [0.5699],
        [0.5699],
        [0.5699],
        [0.5699]], grad_fn=<SigmoidBackward0>)

In [30]:
# show modelweights

# model.linear1.weight

# Access first Linear layer's weights
model.network[0].weight



Parameter containing:
tensor([[-0.1116, -0.2311, -0.4430, -0.1639, -0.2994],
        [ 0.1118, -0.3386, -0.0681, -0.2227, -0.0979],
        [ 0.1167, -0.1120, -0.1780,  0.1907,  0.1334]], requires_grad=True)

In [ ]:
# model.linear1.bias


Parameter containing:
tensor([[-0.3039, -0.4468,  0.0121]], requires_grad=True)

In [32]:
# Access second Linear layer's weights
model.network[2].weight
#model.linear2.weight

Parameter containing:
tensor([[-0.3039, -0.4468,  0.0121]], requires_grad=True)

In [35]:
# model.linear2.bias

print(model.network[0].bias)
print('='*50)
print(model.network[2].bias)


Parameter containing:
tensor([-0.1961, -0.1017, -0.2843], requires_grad=True)
Parameter containing:
tensor([0.2814], requires_grad=True)


In [36]:
pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


In [37]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00