In [2]:
import torch
print(torch.__version__)

2.6.0+cu118


In [5]:
if torch.cuda.is_available():
    print("GPU available")
    print(f"Using Gpu: {torch.cuda.get_device_name(0)}")

else:
    print ("GPU not available.Using CPU")

GPU available
Using Gpu: NVIDIA GeForce RTX 2050


### Creating Tensor

In [11]:
# Using empty
a=torch.empty(3,3) # allocating memomory and displaying the already vaiable value in that memory

In [13]:
# type checking

type(a)

torch.Tensor

In [14]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
# using rand
torch.rand(2,3)# creates tensor of a given shape with ales beteween 0 and 1

tensor([[0.2597, 0.2411, 0.3841],
        [0.5470, 0.4778, 0.9378]])

In [23]:
# use seed
torch.manual_seed(33) # for reproducability
torch.rand(2,3)

tensor([[0.6186, 0.5587, 0.1937],
        [0.3360, 0.2008, 0.6970]])

In [22]:
torch.manual_seed(33)
torch.rand(2,3)

tensor([[0.6186, 0.5587, 0.1937],
        [0.3360, 0.2008, 0.6970]])

In [24]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])